#!/usr/bin/env zsh
# new_machine.sh - for use when cloning dotfiles for the first time

# if the default shell isn't zsh, change it
echo "verifying zsh is the default shell"
[[ $SHELL != '/bin/zsh' ]] && chsh -s /bin/zsh

# clone oh-my-zsh
echo "looking for oh-my-zsh"
[ -d ~/.oh-my-zsh ] || git clone https://github.com/ohmyzsh/ohmyzsh ~/.oh-my-zsh

# clone zsh-syntax-highlighting
[ -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ] || git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# make sure ~/.oh-my-zsh/themes exists
[[ ! -d ~/.oh-my-zsh/themes ]] && mkdir ~/.oh-my-zsh/themes

echo "Checking for SSH key."
[[ -f ~/.ssh/id_rsa.pub ]] || {
  echo "creating ssh key..."
  ssh-keygen -t rsa
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh
}

which brew || {
  echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

xcode-select --install > /dev/null
